---
- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew

- name: Install common applications
  homebrew:
    name:
      - zsh
      - git
      - vim
      - tmux
      - wget
      - curl
      - eza
      - fzf
      - fd
      - zoxide
      - thefuck
      - commitizen
    state: present

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: Install Powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Install zsh-completions plugin
  git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-completions"

- name: Install zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Set Zsh as default shell
  become: true
  shell: chsh -s $(which zsh)

- name: Configure fzf
  shell: "$(brew --prefix)/opt/fzf/install --all"
  args:
    creates: "{{ ansible_env.HOME }}/.fzf.zsh"

- name: Download fzf-git.sh
  get_url:
    url: https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh
    dest: "{{ ansible_env.HOME }}/fzf-git.sh"
