name: Test Ansible Playbook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: pip install ansible

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Create .dotfiles directory
        run: mkdir -p /Users/runner/.dotfiles

      - name: Create .vim/autoload directory
        run: mkdir -p /Users/runner/.vim/autoload

      - name: Debug directory structure
        run: |
          pwd
          echo "Contents of ansible-mac-setup/roles/dotfiles/files/:"
          ls -la ansible-mac-setup/roles/dotfiles/files/
          echo "Contents of /Users/runner/.dotfiles/:"
          ls -la /Users/runner/.dotfiles/
          echo "Contents of /Users/runner/.vim/autoload/:"
          ls -la /Users/runner/.vim/autoload/

      - name: Run Ansible Playbook
        run: |
          cd ansible-mac-setup
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i $PWD/inventory $PWD/playbook.yml --check -vvv

      - name: Verify installed packages
        run: |
          brew list
          brew cask list
